---
- hosts: dev
  user: ansible
  connection: ssh
  become: yes

  tasks:
   - name: collecting link 1
     get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

   - name: collecting key from jenkins.io
     ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

   - name: updating the above two links
     action: yum name= "*" state=latest
  
   - name: install java
     command: amazon-linux-extras install java-openjdk11 -y

   - name: install jenkins
     action: yum name=jenkins state=present

   - name:  reload daemon
     ansible.builtin.systemd:
      daemon_reload: yes

   - name: restart jenkins
     ansible.builtin.systemd:
      name: jenkins
      state: restarted  

