---
- hosts: dev
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: installing HTTPD in server
      action: yum name=httpd state=present
      notify: restart httpd

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted

